# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: sikenali/momowuwen
  branch: main

media_folder: /public/images
public_folder: /images

collections:
  - name: posts
    label: 博客文章
    label_singular: 博客文章
    folder: /content/posts
    path: '{{year}}-{{month}}-{{day}}/{{slug}}'
    fields:
      - { label: 标题, name: title }
      - { label: 日期, name: date, widget: datetime }
      - { label: 摘要, name: description }
      - { label: 标签, name: tags, widget: list, allow_add: true, required: false }
      - { label: 分类, name: category, default: 随笔 }
      - { label: 封面图, name: cover, widget: image, required: false }
      - { label: 草稿, name: draft, widget: boolean, default: false }
      - { label: 正文, name: body, widget: markdown }

  - name: projects
    label: 项目
    label_singular: 项目
    folder: /content/projects
    path: '{{year}}-{{month}}-{{day}}/{{slug}}'
    fields:
      - { label: 项目名称, name: title }
      - { label: 日期, name: date, widget: datetime }
      - { label: 项目简介, name: description }
      - { label: 标签, name: tags, widget: list, allow_add: true, required: false }
      - { label: 分类, name: category, default: 项目 }
      - { label: 封面图, name: cover, widget: image, required: false }
      - { label: 外部链接, name: link, required: false }
      - { label: 草稿, name: draft, widget: boolean, default: false }
      - { label: 项目详情, name: body, widget: markdown }
