backend:
  name: github
  repo: sikenali/momowuwen
  branch: main
  auth_type: code
  base_url: https://www.10012049.xyz
  auth_endpoint: api/oauth

locale: zh_Hans

media_folder: public/images
public_folder: /images

collections:
  - name: 'posts'
    label: '博客文章'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: '日期', name: 'date', widget: 'datetime' }
      - { label: '摘要', name: 'description', widget: 'string' }
      - { label: '标签', name: 'tags', widget: 'list', allow_add: true, required: false }
      - { label: '分类', name: 'category', widget: 'string', default: '随笔' }
      - { label: '封面图', name: 'cover', widget: 'image', required: false }
      - { label: '草稿', name: 'draft', widget: 'boolean', default: false, hint: '勾选后不会在网站上显示' }
      - { label: '正文', name: 'body', widget: 'markdown' }

  - name: 'projects'
    label: '项目'
    folder: 'content/projects'
    Create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: '项目名称', name: 'title', widget: 'string' }
      - { label: '日期', name: 'date', widget: 'datetime' }
      - { label: '项目简介', name: 'description', widget: 'string' }
      - { label: '标签', name: 'tags', widget: 'list', allow_add: true, required: false }
      - { label: '分类', name: 'category', widget: 'string', default: '项目' }
      - { label: '封面图', name: 'cover', widget: 'image', required: false }
      - { label: '外部链接', name: 'link', widget: 'string', required: false }
      - { label: '草稿', name: 'draft', widget: 'boolean', default: false, hint: '勾选后不会在网站上显示' }
      - { label: '项目详情', name: 'body', widget: 'markdown' }
